name: Test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
          cache: poetry

      - name: Install project
        run: poetry install --no-interaction

      - name: Test
        run: poetry run poe test
